name=SO2Predictor-TinyML
version=1.0.0
author=Robert Makomere, rsomeo@yahoo.com
maintainer=Robert Makomere, rsomeo@yahoo.com
sentence=TinyML SO2 removal prediction deployed on ESP32
paragraph=Deployment of a TensorFlowLite Micro model using EloquentTinyML on an ESP32 board to predict SO2 removal efficiency based on four input features.
category=Machine Learning
url=https://github.com/Someo94/SO2Predictor-TinyML
architectures=*
includes=so2_prediction.ino
